# Generated by Django 4.0.5 on 2022-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='tokens',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
