# Generated by Django 4.0.5 on 2022-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_appuser_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='tokens',
            field=models.FloatField(verbose_name=0),
        ),
    ]
