# Generated by Django 4.0.5 on 2022-06-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_report_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
