# Generated by Django 4.0.5 on 2022-06-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='/images/default.jpg', upload_to='images/'),
        ),
    ]
