import Head from "next/head";
import { useEffect, useState } from "react";
import logoutPNG from "../assets/logout.png";
import { useRouter } from "next/router";
import axiosApiInstance from "../utils/axiosConfig";
import Logout from "../utils/Logout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" text-green-500 underline">
        Welcome to EcoTech Recyclers
      </div>
    </div>
  );
}
