import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <div className=" text-green-500 underline">
          Welcome to EcoTech Recyclers
        </div>
      </Head>
    </div>
  );
}
